name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          sudo docker build -t ${{ env.IMAGE_ADDRESS }} .
          sudo docker push ${{ env.IMAGE_ADDRESS }}
