name: First Workflow

on:
  workflow_dispatch:

  permissions:
  contents: "read"
  id-token: "write"

  push:
    branches:
      - main

  steps:
    - uses: "actions/checkout@v4"

    - uses: "google-github-actions/deploy-cloudrun@v2"
      with:
        image: "us-central1-docker.pkg.dev/cinfo-devops-2023-2/docker/alan:1.0"
        service: "hello-cloud-run"
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Build Docker image
#         run: |
#           "docker build -t ${{ vars.IMAGE_ADDRESS }} ."
#       - name: Push Docker image
#         run: |
#           docker push ${{ vars.IMAGE_ADDRESS }}
