name: First Workflow

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  permissions:
    contents: "read"
    id-token: "write"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
      - uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          image: "us-central1-docker.pkg.dev/cinfo-devops-2023-2/docker/alan:1.0"
          service: "hello-cloud-run"
