name: First Workflow

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.IMAGE_ADDRESS }} .
      - name: Push Docker image
        run: |
          docker push ${{ vars.IMAGE_ADDRESS }}
