name: First Workflow

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

jobs: 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "hello-cloud-run"
          image: ${{ vars.IMAGE_ADDRESS }}
          platform: "managed"
          region: "us-central1"
          # service-account-key: ${{ secrets.GCP_SA_KEY }}
```